# Generated by Django 5.0.6 on 2024-08-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregables',
            old_name='fecha_de_entrega',
            new_name='fecha',
        ),
    ]
