# Generated by Django 5.0.6 on 2024-08-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcoder', '0002_rename_fecha_de_entrega_entregables_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('entrega', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Entregables',
        ),
    ]
